sudo: required
services:
- docker
language: python
python:
- '2.7'
script:
- docker build -t yadage/yadage-service:git-"$TRAVIS_BRANCH" .
- docker login -u $DOCKERLOGIN -p $(echo $DOCKERPW|base64 -d)
- docker push yadage/yadage-service:git-"$TRAVIS_BRANCH"
env:
  global:
  - secure: L2YAHJtL0da/jK8unM62jo/JuzQJ9NFP0NUlOay9/d0O9BPf9HYRx00NX1YqIMxXH+Lgs0vUUjXAyyu1OI91Zbw28waA8ZEr7tVZJXgjO32HiK9weey/HnLW7yBcXyU+fpwpS+UCVwFHX82/BK5gIhb5ozzq3uQiC6HREZfZknR9ZsKgluCK1Y0Lb5TbpGwwmfZLrJaiuys/7Ld9UBYOiKUMCTW70WL9lvZAPP2fAGboiVla/ueY+jHO5uIqjH0zLy/CAXoO4BRe/gEm3Ob4az3L/erMer2pkxnseDz05QCBbQQkA1tpvPTXjPNhFA8GeLhVwyVRHVZ19yRSX1Mv2/riO43HxQFJEMA+5jz4hBR0VFlWsYNtp0qhpDAH+1PfRXNN+56pWBgE/kycKIUNjoaWRTkUXkrc6fddkL+v4a/YkMqBhphT0wr0rzMIQtNsiTJMtrs/PO1aSS+axiFqaHietBcvkFqyc65SAjR7WRssbCtm3Vmufyevm8mh9Qt0RIwOREIRrENJynmsr0F6kWqgVhwJtGVgxzGwLoz3hpPdFoe0Ys+oHDpCukyXJmEX9JxkLyBLTIPyjTr9EqB24MCjYQuFLNlaOrzQ9XRFXVbzf6s10Hel3vlHXmAIf0A1ubAm8Z2491jL/USP9O6JvmKr6fKVI3K4emiMiWFcdNI=
  - secure: rS8h8TqzCs/Onq2ClkCgt/TsyoIfNXXNdORr2X2GRkLJLWv6Jl4iu99GMxTXXoWDmxGFiFQRYKk3TSJoEBb06tn8dn/088KSo3971XvMUXPBQDfq1lm/6279XLFgrKzbjAE5vIutIAlYESt+iA2FbMDWwl7KXGVkOXmhDUs9HR2F7d7dwMwrLX/uqcbNtySl9+gRn1arhhzHmD80fP3rZSmLOJSSJth5p6o8lOD7k6S6b6wvVoP0jOyRd+RO31Uu99ixpUABInemx6P5F7HL07oemvQI8RTOhafcJgXaS27iypIjaV3jmkSPIvTpUTZFK0xRU6V2nOOvIBJXUFr491/74vKT0psT9zRC1YFGqHvsUxls1ir5pVZYXDfOyViVSC3hMGjM27VvLdDISnaFnl2Oltz6OMVH75/S6916G0tgSPoxB2gfBVFTwjC33RjNueQ5l2JPsw9W9inGj/YmjIKwpX1BpV3WbkvuBe+MXnggl3L+8fUcUit0vg+IsHkPJu+wxMSU6CFt/mE/kpLJU3uopy/2IXlZnWb1MzFZyuuD/EtjxPUcj2KBDWFxXOQsGnQNN+tCa7QIoarXZWn+SSuiz0ioMZp2zed3nU3KUKgAjX7/AfrK+pBD54qZAWNRvRK4VzcERcxSctcecCtWl5KH4ZXd6WolZDCf1U7PykQ=


